# Generated by Django 2.1.1 on 2018-10-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bid_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auction',
            name='current_bid',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
    ]
