# Generated by Django 2.1.1 on 2018-10-11 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Auction', '0002_auto_20181010_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='current_bid',
        ),
        migrations.AddField(
            model_name='auction',
            name='last_bidder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
    ]
